import { Paint } from ".";

const base: Array<Paint> = [
  { name: "Corax White", color: "#FFFFFF", finish: "Satin", range: "Base" },
  { name: "Grey Seer", color: "#A2A5A7", finish: "Satin", range: "Base" },
  { name: "Celestra Grey", color: "#8BA3A3", finish: "Satin", range: "Base" },
  { name: "Averland Sunset", color: "#FBB81B", finish: "Satin", range: "Base" },
  { name: "Jokaero Orange", color: "#EC3815", finish: "Satin", range: "Base" },
  { name: "Khorne Red", color: "#650101", finish: "Satin", range: "Base" },
  { name: "Mephiston Red", color: "#950C0A", finish: "Satin", range: "Base" },
  { name: "Gal Vobrak Red", color: "#4B213C", finish: "Satin", range: "Base" },
  {
    name: "Barak-Nar Burgundy",
    color: "#441636",
    finish: "Satin",
    range: "Base",
  },
  { name: "Screamer Pink", color: "#7A0F44", finish: "Satin", range: "Base" },
  { name: "Daemonette Hide", color: "#655F80", finish: "Satin", range: "Base" },
  {
    name: "Phoenician Purple",
    color: "#440052",
    finish: "Satin",
    range: "Base",
  },
  { name: "Naggaroth Night", color: "#3B2B50", finish: "Satin", range: "Base" },
  { name: "Caledor Sky", color: "#366699", finish: "Satin", range: "Base" },
  { name: "Macragge Blue", color: "#0F3D7C", finish: "Satin", range: "Base" },
  { name: "Kantor Blue", color: "#01144E", finish: "Satin", range: "Base" },
  {
    name: "Night Lords Blue",
    color: "#012B5C",
    finish: "Satin",
    range: "Base",
  },
  {
    name: "Thousand Sons Blue",
    color: "#00506F",
    finish: "Satin",
    range: "Base",
  },
  {
    name: "Stegadon Scale Green",
    color: "#07455D",
    finish: "Satin",
    range: "Base",
  },
  { name: "Lupercal Green", color: "#002C2B", finish: "Satin", range: "Base" },
  { name: "Incubi Darkness", color: "#092E32", finish: "Satin", range: "Base" },
  {
    name: "Death Guard Green",
    color: "#6D774D",
    finish: "Satin",
    range: "Base",
  },
  {
    name: "Deathworld Forest",
    color: "#546229",
    finish: "Satin",
    range: "Base",
  },
  { name: "Castellan Green", color: "#264715", finish: "Satin", range: "Base" },
  {
    name: "Death Korps Drab  ",
    color: "#3D4539",
    finish: "Satin",
    range: "Base",
  },
  { name: "Waaagh! Flesh", color: "#0B3B36", finish: "Satin", range: "Base" },
  { name: "Caliban Green", color: "#013D15", finish: "Satin", range: "Base" },
  { name: "Nocturne Green", color: "#172929", finish: "Satin", range: "Base" },
  { name: "Wraithbone", color: "#DAD0B2", finish: "Satin", range: "Base" },
  { name: "Morghast Bone", color: "#C0A973", finish: "Satin", range: "Base" },
  { name: "Zandri Dust", color: "#978D56", finish: "Satin", range: "Base" },
  { name: "XV-88", color: "#6C4811", finish: "Satin", range: "Base" },
  {
    name: "Steel Legion Drab",
    color: "#574D2D",
    finish: "Satin",
    range: "Base",
  },
  { name: "Mournfang Brown", color: "#491006", finish: "Satin", range: "Base" },
  { name: "Rhinox Hide", color: "#462F2F", finish: "Satin", range: "Base" },
  { name: "Dryad Bark", color: "#2B2A24", finish: "Satin", range: "Base" },
  { name: "Ionrach Skin", color: "#96A384", finish: "Satin", range: "Base" },
  { name: "Rakarth Flesh", color: "#9B998D", finish: "Satin", range: "Base" },
  { name: "Ratskin Flesh", color: "#A86648", finish: "Satin", range: "Base" },
  { name: "Bugman's Glow", color: "#804B42", finish: "Satin", range: "Base" },
  { name: "Catachan Flesh", color: "#432B25", finish: "Satin", range: "Base" },
  { name: "The Fang", color: "#405B71", finish: "Satin", range: "Base" },
  {
    name: "Mechanicus Standard Grey",
    color: "#39484A",
    finish: "Satin",
    range: "Base",
  },
  { name: "Corvus Black", color: "#171314", finish: "Satin", range: "Base" },
  { name: "Abaddon Black", color: "#000000", finish: "Satin", range: "Base" },
  { name: "Orruk Flesh", color: "#8BC276", finish: "Satin", range: "Base" },
  { name: "Hobgrot Hide", color: "#A1812B", finish: "Satin", range: "Base" },
  { name: "Thondia Brown", color: "#54302A", finish: "Satin", range: "Base" },
];

const paints = [...base];

export default paints;
